name: Tests and quality checks

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 12
          cache: 'yarn'

      - name: Install dependencies
        run: docker-compose run app yarn

      - name: Run build
        run: docker-compose run app yarn build

      - name: Run Lint tests
        run: docker-compose run app yarn lint

      - name: Run tests
        run: docker-compose run app yarn test